OPTION(Archive_HDF5 "Enable HDF5 Archives" ON)
if(Archive_HDF5)
 OPTION(Archive_USE_STATIC_HDF5 "Link static HDF5 Archives" ON)
 if(Archive_USE_STATIC_HDF5)
  set(HDF5_USE_STATIC_LIBRARIES ON)
 endif()
endif()
OPTION(Archive_MATLAB "Enable MATLAB Archives" ON)
OPTION(Archive_ConfigFile "Enable ConfigFiles" ON)
OPTION(Archive_CerealWrappers "Enable CerealWrappers" OFF)
OPTION(Archive_ProgramOptions_Wrapper "Enable Boost Program_Options_Wrapper" ON)